const DEFCARDS = [
    { src: "./assets/img/nature/1.jpeg", isActive: false },
    { src: "./assets/img/nature/2.jpeg", isActive: false },
    { src: "./assets/img/nature/3.jpeg", isActive: false },
    { src: "./assets/img/nature/4.jpeg", isActive: false },
    { src: "./assets/img/nature/5.jpeg", isActive: false },
    { src: "./assets/img/nature/6.jpeg", isActive: false },
    { src: "./assets/img/nature/7.jpeg", isActive: false },
    { src: "./assets/img/nature/8.jpeg", isActive: false },
    { src: "./assets/img/nature/9.jpeg", isActive: false },
    { src: "./assets/img/nature/10.jpeg", isActive: false },
    { src: "./assets/img/nature/11.jpeg", isActive: false },
    { src: "./assets/img/nature/12.jpeg", isActive: false },
    { src: "./assets/img/nature/13.jpeg", isActive: false },
    { src: "./assets/img/nature/14.jpeg", isActive: false },
    { src: "./assets/img/nature/15.jpeg", isActive: false },
    { src: "./assets/img/nature/16.jpeg", isActive: false },
    { src: "./assets/img/nature/17.jpeg", isActive: false },
    { src: "./assets/img/nature/18.jpeg", isActive: false },
    { src: "./assets/img/nature/1.jpeg", isActive: false },
    { src: "./assets/img/nature/2.jpeg", isActive: false },
    { src: "./assets/img/nature/3.jpeg", isActive: false },
    { src: "./assets/img/nature/4.jpeg", isActive: false },
    { src: "./assets/img/nature/5.jpeg", isActive: false },
    { src: "./assets/img/nature/6.jpeg", isActive: false },
    { src: "./assets/img/nature/7.jpeg", isActive: false },
    { src: "./assets/img/nature/8.jpeg", isActive: false },
    { src: "./assets/img/nature/9.jpeg", isActive: false },
    { src: "./assets/img/nature/10.jpeg", isActive: false },
    { src: "./assets/img/nature/11.jpeg", isActive: false },
    { src: "./assets/img/nature/12.jpeg", isActive: false },
    { src: "./assets/img/nature/13.jpeg", isActive: false },
    { src: "./assets/img/nature/14.jpeg", isActive: false },
    { src: "./assets/img/nature/15.jpeg", isActive: false },
    { src: "./assets/img/nature/16.jpeg", isActive: false },
    { src: "./assets/img/nature/17.jpeg", isActive: false },
    { src: "./assets/img/nature/18.jpeg", isActive: false },
]

export { DEFCARDS };